# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_blink/mb_blink.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink || ORIG_REF_NAME==mb_blink} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_microblaze_0_0/mb_blink_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_microblaze_0_0 || ORIG_REF_NAME==mb_blink_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_dlmb_v10_0/mb_blink_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_dlmb_v10_0 || ORIG_REF_NAME==mb_blink_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_ilmb_v10_0/mb_blink_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_ilmb_v10_0 || ORIG_REF_NAME==mb_blink_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_dlmb_bram_if_cntlr_0/mb_blink_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_blink_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_ilmb_bram_if_cntlr_0/mb_blink_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_blink_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_lmb_bram_0/mb_blink_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_lmb_bram_0 || ORIG_REF_NAME==mb_blink_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_xbar_0/mb_blink_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_xbar_0 || ORIG_REF_NAME==mb_blink_xbar_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_microblaze_0_axi_periph_0/mb_blink_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_blink_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_microblaze_0_axi_intc_0/mb_blink_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_blink_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_mdm_1_0/mb_blink_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_mdm_1_0 || ORIG_REF_NAME==mb_blink_mdm_1_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_clk_wiz_1_0/mb_blink_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_clk_wiz_1_0 || ORIG_REF_NAME==mb_blink_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_rst_clk_wiz_1_100M_0/mb_blink_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_blink_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_axi_uartlite_0_0/mb_blink_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_axi_uartlite_0_0 || ORIG_REF_NAME==mb_blink_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_axi_gpio_0_1/mb_blink_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_axi_gpio_0_1 || ORIG_REF_NAME==mb_blink_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_axi_gpio_0_2/mb_blink_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_axi_gpio_0_2 || ORIG_REF_NAME==mb_blink_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_axi_timer_0_0/mb_blink_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_axi_timer_0_0 || ORIG_REF_NAME==mb_blink_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_axi_quad_spi_0_0/mb_blink_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_blink_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_xlconcat_0_0/mb_blink_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_xlconcat_0_0 || ORIG_REF_NAME==mb_blink_xlconcat_0_0} -quiet] -quiet

# IP: bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/mb_blink_hdmi_text_controller_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_blink_hdmi_text_controller_0_1 || ORIG_REF_NAME==mb_blink_hdmi_text_controller_0_1} -quiet] -quiet

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/mb_blink_ooc.xdc
