# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kakkar3/Desktop/Final_Project/Final_Project.srcs/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/mb_blink_hdmi_text_controller_0_1.xci
# IP: The module: 'mb_blink_hdmi_text_controller_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/start_audio_rom/start_audio_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==start_audio_rom || ORIG_REF_NAME==start_audio_rom} -quiet] -quiet

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/background_bram/background_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==background_bram || ORIG_REF_NAME==background_bram} -quiet] -quiet

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/sprite_bram/sprite_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sprite_bram || ORIG_REF_NAME==sprite_bram} -quiet] -quiet

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/start_audio_rom/start_audio_rom_ooc.xdc

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/background_bram/background_bram_ooc.xdc

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/sprite_bram/sprite_bram_ooc.xdc

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: C:/Users/kakkar3/Desktop/Final_Project/Final_Project.srcs/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/mb_blink_hdmi_text_controller_0_1.xci
# IP: The module: 'mb_blink_hdmi_text_controller_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/start_audio_rom/start_audio_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==start_audio_rom || ORIG_REF_NAME==start_audio_rom} -quiet] -quiet

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/background_bram/background_bram.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==background_bram || ORIG_REF_NAME==background_bram} -quiet] -quiet

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/sprite_bram/sprite_bram.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sprite_bram || ORIG_REF_NAME==sprite_bram} -quiet] -quiet

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/start_audio_rom/start_audio_rom_ooc.xdc

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/background_bram/background_bram_ooc.xdc

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/sprite_bram/sprite_bram_ooc.xdc

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/kakkar3/Desktop/Final_Project/Final_Project.gen/sources_1/bd/mb_blink/ip/mb_blink_hdmi_text_controller_0_1/src/clk_wiz_0/clk_wiz_0_ooc.xdc
